#!/bin/sh

INPUT_GENE_LIST=$1
PROJECT_DIR=$2
## PROJECT_DIR=/tcga_next_gen/TCGA_WholeGenome/SubAnalysis/SOMATIC_RESULT
## VALIDATE_MUTATION_FILE=${ROOT_DIR}/validate_somatic_loci.txt
VALIDATE_MUTATION_FILE=$3

SAMPLE_FILE=$4
PROJECT_LABEL=$5  ## TCGA_OV

DEBUG_LEVEL=$6
LOG=$7


SCRIPT_DIR=/user/songliu/u2/group/Qiang/Exome/scripts/snp_postprocess/snv_postprocess
MAP_SCRIPT=${SCRIPT_DIR}/map_GSC_SNP


if test ! -s ${INPUT_GENE_LIST}
then
if [ $DEBUG_LEVEL -gt 0 ]
then
  echo "Fail to find input gene list ${INPUT_GENE_LIST} for map_all_somatic_mutation" >> $LOG
  fi
exit 1
fi

if test ! -d ${PROJECT_DIR}
then
  if [ $DEBUG_LEVEL -gt 0 ]
then
echo "Fail to find directory ${PROJECT_DIR} in map_all_somatic_mutation" >> $LOG
  fi
exit 1
fi

if test ! -s ${VALIDATE_MUTATION_FILE}
then
  if [ $DEBUG_LEVEL -gt 0 ]
then
echo "Fail to find validated mutation file ${VALIDATE_MUTATION_FILE} for map_all_somatic_mutation" >> $LOG
  fi
exit 1
fi

if test ! -s ${SAMPLE_FILE}
then
  if [ $DEBUG_LEVEL -gt 0 ]
then
echo "Fail to find sample file ${SAMPLE_FILE} for map_all_somatic_mutation" >> $LOG
  fi
exit 1
fi

for i in `cat ${INPUT_GENE_LIST}`; do
  cd ${PROJECT_DIR}
  ${MAP_SCRIPT} $i `pwd` ${PROJECT_LABEL} ${SAMPLE_FILE} ${VALIDATE_MUTATION_FILE} somatic
done
